title: Sam Bellenchia
logo: "images/logo.png"
theme: jekyll-theme-leap-day
google-analytics: G-YVSWD20NSW
description: >
  
  <div align="center">
    <br><br>
    <b>Teaching Assistant<b>
    <p>Northwestern University Data Science Boot Camp<p>
    <br><br>
  <a id="linkedin" href="https://www.linkedin.com/in/sbellenchia/">LinkedIn  </a> 
  <a id="github" href="https://www.github.com/Schlam/">GitHub  </a> 
  <a id="twitter" href="https://www.twitter.com/SamBellenchia/">Twitter  </a> 
  </div>
  