title: Samuel C Bellenchia # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br><br>
  <b>Teaching Assistant<b>
  Northwestern University Data Science Boot Camp
  <br><br>
  <a href="https://www.linkedin.com/in/example/">LinkedIn</a> 
  <a href="https://www.github.com/Schlam/">GitHub</a> 
  <a href="https://www.twitter.com/SamBellenchia/">Twitter</a> 
  
theme: jekyll-theme-minimal
google-analytics: G-YVSWD20NSW