title: Sam Bellenchia # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A portfolio to showcase some of my 
  <br><br>
  interests, 
  <br><br>
  skills,
  <br><br>
  and experiences
  <br><br>
  <a href="https://www.linkedin.com/in/example/">LinkedIn</a> 
  <a href="https://www.github.com/Schlam/">GitHub</a> 
  <a href="https://www.twitter.com/SamBellenchia/">Twitter</a> 
  
theme: jekyll-theme-minimal
google-analytics: G-YVSWD20NSW