title: Sam Bellenchia
logo: "images/logo.png"
description: >
  <br><br>
  <h2>Teaching Assistant</h2>
  <h3>Northwestern University Data Science Boot Camp</h3>
  <br><br>
  <div align="center">
    <a style="color:black" href="https://www.linkedin.com/in/example/">LinkedIn  </a> 
    <a style="color:black" href="https://www.github.com/Schlam/">GitHub  </a> 
    <a style="color:black" href="https://www.twitter.com/SamBellenchia/">Twitter  </a> 
  </div>
theme: jekyll-theme-minimal
# google-analytics: G-YVSWD20NSW